applications= [
    {
        "applicationId": "APP9001",
        "studentId": "STU1097",
        "driveId": "DRV128",
        "appliedAt": "2026-09-08",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9002",
        "studentId": "STU1046",
        "driveId": "DRV107",
        "appliedAt": "2026-11-14",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9003",
        "studentId": "STU1020",
        "driveId": "DRV143",
        "appliedAt": "2026-11-02",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9004",
        "studentId": "STU1045",
        "driveId": "DRV136",
        "appliedAt": "2026-10-19",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9005",
        "studentId": "STU1074",
        "driveId": "DRV115",
        "appliedAt": "2026-10-26",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9006",
        "studentId": "STU1078",
        "driveId": "DRV143",
        "appliedAt": "2026-11-29",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9007",
        "studentId": "STU1024",
        "driveId": "DRV118",
        "appliedAt": "2026-11-30",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9008",
        "studentId": "STU1045",
        "driveId": "DRV101",
        "appliedAt": "2026-09-25",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9009",
        "studentId": "STU1009",
        "driveId": "DRV110",
        "appliedAt": "2026-11-22",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9010",
        "studentId": "STU1096",
        "driveId": "DRV134",
        "appliedAt": "2026-09-29",
        "currentRound": "HR",
        "status": "rejected",
    },
    {
        "applicationId": "APP9011",
        "studentId": "STU9999",
        "driveId": "DRV122",
        "appliedAt": "2026-09-22",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9012",
        "studentId": "STU1093",
        "driveId": "DRV999",
        "appliedAt": "2026-11-13",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9013",
        "studentId": "STU1007",
        "driveId": "DRV110",
        "appliedAt": "2026-09-22",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9014",
        "studentId": "STU1087",
        "driveId": "DRV106",
        "appliedAt": "bad-date",
        "currentRound": "HR",
        "status": "rejected",
    },
    {
        "applicationId": "APP9015",
        "studentId": "STU1063",
        "driveId": "DRV139",
        "appliedAt": "2026-10-28",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9016",
        "studentId": "STU1028",
        "driveId": "DRV149",
        "appliedAt": "2026-11-06",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9017",
        "studentId": "STU1056",
        "driveId": "DRV108",
        "appliedAt": "2026-10-08",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9018",
        "studentId": "STU1068",
        "driveId": "DRV143",
        "appliedAt": "2026-10-11",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9019",
        "studentId": "STU1051",
        "driveId": "DRV139",
        "appliedAt": "2026-09-09",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9020",
        "studentId": "STU1039",
        "driveId": "DRV114",
        "appliedAt": "2026-09-19",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9021",
        "studentId": "STU1042",
        "driveId": "DRV108",
        "appliedAt": "2026-09-02",
        "currentRound": "HR",
        "status": "rejected",
    },
    {
        "applicationId": "APP9022",
        "studentId": "STU1023",
        "driveId": "DRV109",
        "appliedAt": "2026-10-20",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9023",
        "studentId": "STU1065",
        "driveId": "DRV136",
        "appliedAt": "2026-11-26",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9024",
        "studentId": "STU1051",
        "driveId": "DRV148",
        "appliedAt": "2026-09-07",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9025",
        "studentId": "STU1059",
        "driveId": "DRV105",
        "appliedAt": "2026-10-12",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9026",
        "studentId": "STU1074",
        "driveId": "DRV126",
        "appliedAt": "2026-11-22",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9027",
        "studentId": "STU1015",
        "driveId": "DRV126",
        "appliedAt": "2026-09-04",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9028",
        "studentId": "STU1080",
        "driveId": "DRV130",
        "appliedAt": "2026-11-29",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9029",
        "studentId": "STU1056",
        "driveId": "DRV107",
        "appliedAt": "2026-10-03",
        "currentRound": "HR",
        "status": "rejected",
    },
    {
        "applicationId": "APP9030",
        "studentId": "STU1068",
        "driveId": "DRV106",
        "appliedAt": "2026-10-22",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9031",
        "studentId": "STU1029",
        "driveId": "DRV122",
        "appliedAt": "2026-09-23",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9032",
        "studentId": "STU1068",
        "driveId": "DRV133",
        "appliedAt": "2026-09-26",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9033",
        "studentId": "STU1094",
        "driveId": "DRV142",
        "appliedAt": "2026-09-20",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9034",
        "studentId": "STU1019",
        "driveId": "DRV117",
        "appliedAt": "2026-09-27",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9035",
        "studentId": "STU1098",
        "driveId": "DRV149",
        "appliedAt": "2026-11-24",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9036",
        "studentId": "STU1099",
        "driveId": "DRV141",
        "appliedAt": "2026-11-04",
        "currentRound": "HR",
        "status": "rejected",
    },
    {
        "applicationId": "APP9037",
        "studentId": "STU1088",
        "driveId": "DRV137",
        "appliedAt": "2026-11-23",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9038",
        "studentId": "STU1081",
        "driveId": "DRV121",
        "appliedAt": "2026-09-21",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9039",
        "studentId": "STU1061",
        "driveId": "DRV129",
        "appliedAt": "2026-11-21",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9040",
        "studentId": "STU1076",
        "driveId": "DRV104",
        "appliedAt": "2026-10-17",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9041",
        "studentId": "STU1040",
        "driveId": "DRV130",
        "appliedAt": "2026-10-29",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9042",
        "studentId": "STU1048",
        "driveId": "DRV119",
        "appliedAt": "2026-09-11",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9043",
        "studentId": "STU1060",
        "driveId": "DRV138",
        "appliedAt": "2026-11-11",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9044",
        "studentId": "STU1074",
        "driveId": "DRV142",
        "appliedAt": "2026-09-26",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9045",
        "studentId": "STU1065",
        "driveId": "DRV110",
        "appliedAt": "2026-09-09",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9046",
        "studentId": "STU1044",
        "driveId": "DRV146",
        "appliedAt": "2026-09-12",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9047",
        "studentId": "STU1006",
        "driveId": "DRV116",
        "appliedAt": "2026-10-28",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9048",
        "studentId": "STU1047",
        "driveId": "DRV124",
        "appliedAt": "2026-10-08",
        "currentRound": "HR",
        "status": "rejected",
    },
    {
        "applicationId": "APP9049",
        "studentId": "STU1100",
        "driveId": "DRV122",
        "appliedAt": "2026-11-27",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9050",
        "studentId": "STU1081",
        "driveId": "DRV142",
        "appliedAt": "2026-10-14",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9051",
        "studentId": "STU1013",
        "driveId": "DRV136",
        "appliedAt": "2026-11-27",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9052",
        "studentId": "STU1033",
        "driveId": "DRV147",
        "appliedAt": "2026-11-25",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9053",
        "studentId": "STU1043",
        "driveId": "DRV106",
        "appliedAt": "2026-11-15",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9054",
        "studentId": "STU1040",
        "driveId": "DRV142",
        "appliedAt": "2026-11-30",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9055",
        "studentId": "STU1077",
        "driveId": "DRV146",
        "appliedAt": "2026-09-12",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9056",
        "studentId": "STU1083",
        "driveId": "DRV122",
        "appliedAt": "2026-09-18",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9057",
        "studentId": "STU1083",
        "driveId": "DRV143",
        "appliedAt": "2026-10-26",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9058",
        "studentId": "STU1003",
        "driveId": "DRV124",
        "appliedAt": "2026-10-11",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9059",
        "studentId": "STU1044",
        "driveId": "DRV150",
        "appliedAt": "2026-11-03",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9060",
        "studentId": "STU1018",
        "driveId": "DRV110",
        "appliedAt": "2026-09-11",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9061",
        "studentId": "STU1065",
        "driveId": "DRV150",
        "appliedAt": "2026-11-10",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9062",
        "studentId": "STU1085",
        "driveId": "DRV122",
        "appliedAt": "2026-11-20",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9063",
        "studentId": "STU1020",
        "driveId": "DRV111",
        "appliedAt": "2026-09-25",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9064",
        "studentId": "STU1093",
        "driveId": "DRV129",
        "appliedAt": "2026-09-07",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9065",
        "studentId": "STU1087",
        "driveId": "DRV147",
        "appliedAt": "2026-10-02",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9066",
        "studentId": "STU1097",
        "driveId": "DRV148",
        "appliedAt": "2026-10-29",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9067",
        "studentId": "STU1040",
        "driveId": "DRV131",
        "appliedAt": "2026-09-26",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9068",
        "studentId": "STU1060",
        "driveId": "DRV150",
        "appliedAt": "2026-10-08",
        "currentRound": "HR",
        "status": "rejected",
    },
    {
        "applicationId": "APP9069",
        "studentId": "STU1021",
        "driveId": "DRV113",
        "appliedAt": "2026-11-18",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9070",
        "studentId": "STU1007",
        "driveId": "DRV142",
        "appliedAt": "2026-11-02",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9071",
        "studentId": "STU1092",
        "driveId": "DRV134",
        "appliedAt": "2026-09-17",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9072",
        "studentId": "STU1098",
        "driveId": "DRV111",
        "appliedAt": "2026-10-06",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9073",
        "studentId": "STU1056",
        "driveId": "DRV106",
        "appliedAt": "2026-09-30",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9074",
        "studentId": "STU1004",
        "driveId": "DRV127",
        "appliedAt": "2026-09-08",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9075",
        "studentId": "STU1031",
        "driveId": "DRV125",
        "appliedAt": "2026-09-12",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9076",
        "studentId": "STU1004",
        "driveId": "DRV121",
        "appliedAt": "2026-09-14",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9077",
        "studentId": "STU1018",
        "driveId": "DRV103",
        "appliedAt": "2026-10-08",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9078",
        "studentId": "STU1098",
        "driveId": "DRV146",
        "appliedAt": "2026-11-01",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9079",
        "studentId": "STU1011",
        "driveId": "DRV102",
        "appliedAt": "2026-10-04",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9080",
        "studentId": "STU1071",
        "driveId": "DRV147",
        "appliedAt": "2026-11-18",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9081",
        "studentId": "STU1015",
        "driveId": "DRV150",
        "appliedAt": "2026-10-08",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9082",
        "studentId": "STU1016",
        "driveId": "DRV104",
        "appliedAt": "2026-10-02",
        "currentRound": "HR",
        "status": "rejected",
    },
    {
        "applicationId": "APP9083",
        "studentId": "STU1009",
        "driveId": "DRV108",
        "appliedAt": "2026-11-04",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9084",
        "studentId": "STU1081",
        "driveId": "DRV133",
        "appliedAt": "2026-11-14",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9085",
        "studentId": "STU1038",
        "driveId": "DRV128",
        "appliedAt": "2026-09-02",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9086",
        "studentId": "STU1031",
        "driveId": "DRV137",
        "appliedAt": "2026-10-25",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9087",
        "studentId": "STU1068",
        "driveId": "DRV124",
        "appliedAt": "2026-09-10",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9088",
        "studentId": "STU1050",
        "driveId": "DRV131",
        "appliedAt": "2026-09-07",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9089",
        "studentId": "STU1033",
        "driveId": "DRV148",
        "appliedAt": "2026-09-04",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9090",
        "studentId": "STU1045",
        "driveId": "DRV116",
        "appliedAt": "2026-11-25",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9091",
        "studentId": "STU1018",
        "driveId": "DRV103",
        "appliedAt": "2026-10-17",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9092",
        "studentId": "STU1083",
        "driveId": "DRV112",
        "appliedAt": "2026-11-28",
        "currentRound": "HR",
        "status": "rejected",
    },
    {
        "applicationId": "APP9093",
        "studentId": "STU1081",
        "driveId": "DRV112",
        "appliedAt": "2026-09-19",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9094",
        "studentId": "STU1005",
        "driveId": "DRV119",
        "appliedAt": "2026-09-27",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9095",
        "studentId": "STU1006",
        "driveId": "DRV121",
        "appliedAt": "2026-10-11",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9096",
        "studentId": "STU1070",
        "driveId": "DRV131",
        "appliedAt": "2026-10-04",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9097",
        "studentId": "STU1037",
        "driveId": "DRV123",
        "appliedAt": "2026-09-08",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9098",
        "studentId": "STU1016",
        "driveId": "DRV124",
        "appliedAt": "2026-10-27",
        "currentRound": "HR",
        "status": "rejected",
    },
    {
        "applicationId": "APP9099",
        "studentId": "STU1050",
        "driveId": "DRV122",
        "appliedAt": "2026-09-25",
        "currentRound": "HR",
        "status": "rejected",
    },
    {
        "applicationId": "APP9100",
        "studentId": "STU1048",
        "driveId": "DRV134",
        "appliedAt": "2026-10-06",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9101",
        "studentId": "STU1011",
        "driveId": "DRV128",
        "appliedAt": "2026-11-18",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9102",
        "studentId": "STU1042",
        "driveId": "DRV107",
        "appliedAt": "2026-09-12",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9103",
        "studentId": "STU1040",
        "driveId": "DRV129",
        "appliedAt": "2026-11-18",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9104",
        "studentId": "STU1089",
        "driveId": "DRV129",
        "appliedAt": "2026-10-16",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9105",
        "studentId": "STU1094",
        "driveId": "DRV123",
        "appliedAt": "2026-11-19",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9106",
        "studentId": "STU1082",
        "driveId": "DRV104",
        "appliedAt": "2026-09-11",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9107",
        "studentId": "STU1066",
        "driveId": "DRV148",
        "appliedAt": "2026-11-27",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9108",
        "studentId": "STU1019",
        "driveId": "DRV139",
        "appliedAt": "2026-11-27",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9109",
        "studentId": "STU1017",
        "driveId": "DRV105",
        "appliedAt": "2026-10-02",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9110",
        "studentId": "STU1050",
        "driveId": "DRV137",
        "appliedAt": "2026-09-06",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9111",
        "studentId": "STU1087",
        "driveId": "DRV129",
        "appliedAt": "2026-10-19",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9112",
        "studentId": "STU1098",
        "driveId": "DRV105",
        "appliedAt": "2026-11-14",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9113",
        "studentId": "STU1051",
        "driveId": "DRV121",
        "appliedAt": "2026-11-24",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9114",
        "studentId": "STU1015",
        "driveId": "DRV102",
        "appliedAt": "2026-09-25",
        "currentRound": "HR",
        "status": "rejected",
    },
    {
        "applicationId": "APP9115",
        "studentId": "STU1072",
        "driveId": "DRV108",
        "appliedAt": "2026-10-05",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9116",
        "studentId": "STU1028",
        "driveId": "DRV140",
        "appliedAt": "2026-10-08",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9117",
        "studentId": "STU1016",
        "driveId": "DRV109",
        "appliedAt": "2026-09-11",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9118",
        "studentId": "STU1092",
        "driveId": "DRV129",
        "appliedAt": "2026-09-13",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9119",
        "studentId": "STU1091",
        "driveId": "DRV105",
        "appliedAt": "2026-11-11",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9120",
        "studentId": "STU1039",
        "driveId": "DRV111",
        "appliedAt": "2026-11-30",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9121",
        "studentId": "STU1066",
        "driveId": "DRV115",
        "appliedAt": "2026-09-17",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9122",
        "studentId": "STU1031",
        "driveId": "DRV132",
        "appliedAt": "2026-09-05",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9123",
        "studentId": "STU1060",
        "driveId": "DRV136",
        "appliedAt": "2026-09-18",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9124",
        "studentId": "STU1009",
        "driveId": "DRV120",
        "appliedAt": "2026-10-22",
        "currentRound": "HR",
        "status": "rejected",
    },
    {
        "applicationId": "APP9125",
        "studentId": "STU1099",
        "driveId": "DRV127",
        "appliedAt": "2026-11-14",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9126",
        "studentId": "STU1041",
        "driveId": "DRV142",
        "appliedAt": "2026-09-11",
        "currentRound": "HR",
        "status": "rejected",
    },
    {
        "applicationId": "APP9127",
        "studentId": "STU1088",
        "driveId": "DRV134",
        "appliedAt": "2026-10-16",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9128",
        "studentId": "STU1099",
        "driveId": "DRV109",
        "appliedAt": "2026-10-27",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9129",
        "studentId": "STU1016",
        "driveId": "DRV134",
        "appliedAt": "2026-09-21",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9130",
        "studentId": "STU1021",
        "driveId": "DRV121",
        "appliedAt": "2026-09-30",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9131",
        "studentId": "STU1011",
        "driveId": "DRV117",
        "appliedAt": "2026-09-27",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9132",
        "studentId": "STU1017",
        "driveId": "DRV141",
        "appliedAt": "2026-10-10",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9133",
        "studentId": "STU1065",
        "driveId": "DRV142",
        "appliedAt": "2026-09-23",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9134",
        "studentId": "STU1022",
        "driveId": "DRV143",
        "appliedAt": "2026-11-20",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9135",
        "studentId": "STU1073",
        "driveId": "DRV103",
        "appliedAt": "2026-09-05",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9136",
        "studentId": "STU1083",
        "driveId": "DRV150",
        "appliedAt": "2026-11-14",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9137",
        "studentId": "STU1099",
        "driveId": "DRV137",
        "appliedAt": "2026-10-25",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9138",
        "studentId": "STU1064",
        "driveId": "DRV141",
        "appliedAt": "2026-11-10",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9139",
        "studentId": "STU1062",
        "driveId": "DRV116",
        "appliedAt": "2026-11-28",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9140",
        "studentId": "STU1059",
        "driveId": "DRV105",
        "appliedAt": "2026-11-29",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9141",
        "studentId": "STU1057",
        "driveId": "DRV127",
        "appliedAt": "2026-11-02",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9142",
        "studentId": "STU1044",
        "driveId": "DRV139",
        "appliedAt": "2026-09-20",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9143",
        "studentId": "STU1094",
        "driveId": "DRV123",
        "appliedAt": "2026-10-23",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9144",
        "studentId": "STU1066",
        "driveId": "DRV136",
        "appliedAt": "2026-09-15",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9145",
        "studentId": "STU1060",
        "driveId": "DRV108",
        "appliedAt": "2026-10-06",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9146",
        "studentId": "STU1019",
        "driveId": "DRV107",
        "appliedAt": "2026-09-08",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9147",
        "studentId": "STU1079",
        "driveId": "DRV127",
        "appliedAt": "2026-10-03",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9148",
        "studentId": "STU1074",
        "driveId": "DRV147",
        "appliedAt": "2026-10-12",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9149",
        "studentId": "STU1064",
        "driveId": "DRV133",
        "appliedAt": "2026-10-31",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9150",
        "studentId": "STU1064",
        "driveId": "DRV102",
        "appliedAt": "2026-09-13",
        "currentRound": "HR",
        "status": "rejected",
    },
    {
        "applicationId": "APP9151",
        "studentId": "STU1031",
        "driveId": "DRV114",
        "appliedAt": "2026-11-15",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9152",
        "studentId": "STU1007",
        "driveId": "DRV119",
        "appliedAt": "2026-11-04",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9153",
        "studentId": "STU1037",
        "driveId": "DRV135",
        "appliedAt": "2026-09-03",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9154",
        "studentId": "STU1018",
        "driveId": "DRV117",
        "appliedAt": "2026-10-18",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9155",
        "studentId": "STU1006",
        "driveId": "DRV126",
        "appliedAt": "2026-09-08",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9156",
        "studentId": "STU1047",
        "driveId": "DRV136",
        "appliedAt": "2026-10-08",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9157",
        "studentId": "STU1065",
        "driveId": "DRV129",
        "appliedAt": "2026-11-11",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9158",
        "studentId": "STU1017",
        "driveId": "DRV107",
        "appliedAt": "2026-10-22",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9159",
        "studentId": "STU1072",
        "driveId": "DRV124",
        "appliedAt": "2026-09-20",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9160",
        "studentId": "STU1065",
        "driveId": "DRV103",
        "appliedAt": "2026-09-07",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9161",
        "studentId": "STU1092",
        "driveId": "DRV122",
        "appliedAt": "2026-11-01",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9162",
        "studentId": "STU1020",
        "driveId": "DRV139",
        "appliedAt": "2026-11-06",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9163",
        "studentId": "STU1079",
        "driveId": "DRV121",
        "appliedAt": "2026-09-22",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9164",
        "studentId": "STU1076",
        "driveId": "DRV122",
        "appliedAt": "2026-11-05",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9165",
        "studentId": "STU1091",
        "driveId": "DRV137",
        "appliedAt": "2026-10-10",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9166",
        "studentId": "STU1048",
        "driveId": "DRV122",
        "appliedAt": "2026-11-27",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9167",
        "studentId": "STU1075",
        "driveId": "DRV120",
        "appliedAt": "2026-11-29",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9168",
        "studentId": "STU1034",
        "driveId": "DRV142",
        "appliedAt": "2026-11-15",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9169",
        "studentId": "STU1093",
        "driveId": "DRV104",
        "appliedAt": "2026-11-15",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9170",
        "studentId": "STU1068",
        "driveId": "DRV141",
        "appliedAt": "2026-11-20",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9171",
        "studentId": "STU1088",
        "driveId": "DRV116",
        "appliedAt": "2026-09-06",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9172",
        "studentId": "STU1025",
        "driveId": "DRV102",
        "appliedAt": "2026-10-28",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9173",
        "studentId": "STU1020",
        "driveId": "DRV127",
        "appliedAt": "2026-11-29",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9174",
        "studentId": "STU1065",
        "driveId": "DRV150",
        "appliedAt": "2026-11-19",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9175",
        "studentId": "STU1091",
        "driveId": "DRV109",
        "appliedAt": "2026-11-07",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9176",
        "studentId": "STU1085",
        "driveId": "DRV131",
        "appliedAt": "2026-11-08",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9177",
        "studentId": "STU1023",
        "driveId": "DRV130",
        "appliedAt": "2026-11-09",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9178",
        "studentId": "STU1087",
        "driveId": "DRV150",
        "appliedAt": "2026-11-28",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9179",
        "studentId": "STU1025",
        "driveId": "DRV116",
        "appliedAt": "2026-10-07",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9180",
        "studentId": "STU1029",
        "driveId": "DRV120",
        "appliedAt": "2026-10-08",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9181",
        "studentId": "STU1041",
        "driveId": "DRV131",
        "appliedAt": "2026-10-16",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9182",
        "studentId": "STU1037",
        "driveId": "DRV108",
        "appliedAt": "2026-11-14",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9183",
        "studentId": "STU1051",
        "driveId": "DRV123",
        "appliedAt": "2026-09-20",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9184",
        "studentId": "STU1037",
        "driveId": "DRV146",
        "appliedAt": "2026-09-12",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9185",
        "studentId": "STU1084",
        "driveId": "DRV117",
        "appliedAt": "2026-11-02",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9186",
        "studentId": "STU1069",
        "driveId": "DRV118",
        "appliedAt": "2026-11-12",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9187",
        "studentId": "STU1014",
        "driveId": "DRV140",
        "appliedAt": "2026-11-16",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9188",
        "studentId": "STU1007",
        "driveId": "DRV143",
        "appliedAt": "2026-11-08",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9189",
        "studentId": "STU1007",
        "driveId": "DRV107",
        "appliedAt": "2026-10-24",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9190",
        "studentId": "STU1013",
        "driveId": "DRV144",
        "appliedAt": "2026-09-19",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9191",
        "studentId": "STU1053",
        "driveId": "DRV142",
        "appliedAt": "2026-11-01",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9192",
        "studentId": "STU1097",
        "driveId": "DRV119",
        "appliedAt": "2026-10-13",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9193",
        "studentId": "STU1099",
        "driveId": "DRV106",
        "appliedAt": "2026-11-24",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9194",
        "studentId": "STU1069",
        "driveId": "DRV148",
        "appliedAt": "2026-09-06",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9195",
        "studentId": "STU1023",
        "driveId": "DRV103",
        "appliedAt": "2026-10-22",
        "currentRound": "HR",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9196",
        "studentId": "STU1096",
        "driveId": "DRV119",
        "appliedAt": "2026-09-06",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9197",
        "studentId": "STU1073",
        "driveId": "DRV139",
        "appliedAt": "2026-09-15",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9198",
        "studentId": "STU1059",
        "driveId": "DRV142",
        "appliedAt": "2026-11-10",
        "currentRound": "Aptitude",
        "status": "applied",
    },
    {
        "applicationId": "APP9199",
        "studentId": "STU1018",
        "driveId": "DRV133",
        "appliedAt": "2026-10-31",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
    {
        "applicationId": "APP9200",
        "studentId": "STU1015",
        "driveId": "DRV122",
        "appliedAt": "2026-09-22",
        "currentRound": "HR",
        "status": "selected",
    },
    {
        "applicationId": "APP9999",
        "studentId": "STU1097",
        "driveId": "DRV128",
        "appliedAt": "2026-09-08",
        "currentRound": "Technical",
        "status": "shortlisted",
    },
]
import json

for application in applications:
    if application["status"] == "selected" or application["status"] == "rejected":
        application["currentRound"] = "Completed"

print(json.dumps(applications, indent=4))

